# Server port for local testing
server.port=8085

# MySQL datasource configuration
spring.datasource.url=jdbc:mysql://database-1.c2nau2o6kxsm.us-east-1.rds.amazonaws.com:3306/usersdb?useSSL=true&requireSSL=true&verifyServerCertificate=true&sslMode=VERIFY_IDENTITY&sslCa=./global-bundle.pem&serverTimezone=UTC
spring.datasource.username=admin
spring.datasource.password=3I-7nAyHb4D(8J[-#0d$#c79hu0k
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Thymeleaf cache disabled for development
spring.thymeleaf.cache=false
